# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
      timezone: UTC
      time: "07:00"
  - package-ecosystem: "npm"
    directory: "angular"
    schedule:
      interval: "monthly"
      timezone: UTC
      time: "07:00"
  - package-ecosystem: "npm"
    directory: "nextjs"
    schedule:
      interval: "monthly"
      timezone: UTC
      time: "07:00"
  - package-ecosystem: "npm"
    directory: "plain"
    schedule:
      interval: "monthly"
      timezone: UTC
      time: "07:00"
  - package-ecosystem: "npm"
    directory: "react-native"
    schedule:
      interval: "monthly"
      timezone: UTC
      time: "07:00"
  - package-ecosystem: "npm"
    directory: "react/cra"
    schedule:
      interval: "monthly"
      timezone: UTC
      time: "07:00"
  - package-ecosystem: "npm"
    directory: "react/esbuild"
    schedule:
      interval: "monthly"
      timezone: UTC
      time: "07:00"
  - package-ecosystem: "npm"
    directory: "react/parcel"
    schedule:
      interval: "monthly"
      timezone: UTC
      time: "07:00"
  - package-ecosystem: "npm"
    directory: "react/rollup"
    schedule:
      interval: "monthly"
      timezone: UTC
      time: "07:00"
  - package-ecosystem: "npm"
    directory: "react/vite"
    schedule:
      interval: "monthly"
      timezone: UTC
      time: "07:00"
  - package-ecosystem: "npm"
    directory: "react/webpack"
    schedule:
      interval: "monthly"
      timezone: UTC
      time: "07:00"
  - package-ecosystem: "npm"
    directory: "react/yarn3-unplugged"
    schedule:
      interval: "monthly"
      timezone: UTC
      time: "07:00"
  - package-ecosystem: "npm"
    directory: "react/yarn3"
    schedule:
      interval: "monthly"
      timezone: UTC
      time: "07:00"
  - package-ecosystem: "npm"
    directory: "remix"
    schedule:
      interval: "monthly"
      timezone: UTC
      time: "07:00"
  - package-ecosystem: "npm"
    directory: "svelte"
    schedule:
      interval: "monthly"
      timezone: UTC
      time: "07:00"
  - package-ecosystem: "npm"
    directory: "vue"
    schedule:
      interval: "monthly"
      timezone: UTC
      time: "07:00"
